- name: provisioning of local machine...
  hosts: all
  sudo: true
  vars:
    myusername: user0
    # shell cmd: mkpasswd --method=sha-512
    mypwd: $6$7XW673ol.ZNKlZS$4oAG4xj0N6GFw9XeDOrYMPcFE5S.nR08FtB1umDlrmcL3VIiBgc6O9L87TL./iBV3HMJ1exuV75iyA40GS7x01 #xxx
    
    tmplfilesdir: '{{ playbook_dir }}/ansible_tmplfiles/'
    defterminal: 'gnome-terminal' #'urxvt'
  # connection: local
  roles:
    - common