---
## https://www.sublimetext.com/docs/3/linux_repositories.html
  - name: set Sublime Text apt file location
    set_fact:
      subl_apt_file: /etc/apt/sources.list.d/sublime-text.list
  
  - name: install GPG key
    shell: wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -

  - name: add Google Chrome repo
    copy: content="deb https://download.sublimetext.com/ apt/stable/" dest={{subl_apt_file}} owner=root group=root mode=644

  - name: update apt cache
    apt: update_cache=yes
    
  - name: install Sublime Text
    apt:
      name: sublime-text 
      state: latest